## Example Config file
BaseURL: "https://austindelarosa.com/"
theme: "terminalcv"
title: "atdlr"

params:
  description: "Austin DeLaRosa - Lead DevOps Engineer"
  prompt: "root@atdlr"
  promptColor: lightblue
  promptSimbols: ":~$"
  # promptSimbolsColor: grey
  startxLocation: https://twitter.com/lucashennessey
  # hideSocialName: true
  exitLocation: "about:blank"
  # hidesource: true
  greeting: |
    Welcome to my terminal curriculum vitae

    Type 'help' for a list of available commands

  whois:
    name: "Austin DeLaRosa"
    profession: "Lead DevOps Engineer"
    location: "Cincinnati, Ohio"
    email: "austin.delarosa@gmail.com"
    homelink: "https://www.austindelarosa.com"
    description: |
      This site is under construction

  social:
    ## IF you want to keep them aligned just add spaces
    - name: "github"
      url: "          https://github.com/delarooster"
    - name: "linkedin"
      url: "        https://www.linkedin.com/in/austindelarosa"

  work:
    - jobTitle: Lead DevOps Engineer
      color: gold
      company: Mesh Systems
      location: remote
      date: August 2022 - Present
      #description: |

    - jobTitle: DevOps Engineer
      color: white
      company: Mesh Systems
      location: remote
      date: August 2021 - August 2022
      #description: |

    - jobTitle: Software Engineer
      color: blue
      company: The David J. Joseph Company (DJJ)
      location: Cincinnati, Ohio
      date: January 2020 - August 2021
      #description: |

    - jobTitle: Software Engineer
      color: green
      company: Organized Living
      location: Sharonville, Ohio
      date: 2019
      #description: |

    - jobTitle: Software Engineer
      color: orange
      company: Atricure
      location: Mason, Ohio
      date: 2018 - 2019
      #description: |

    - jobTitle: Web Developer
      color: blue
      company: Mackin & Sons Plumbing
      location: remote
      date: 2016 - 2018
      #description: |

  education:
    - courseName: DePauw University
      color: gold
      description: |
        Bachelor of Music
        ITAP

    - courseName: Butler University
      color: white
      description: |
        Master of Music

    - courseName: Tech Elevator
      color: blue
      description: |
        Computer Science

  skills:
    - name: Azure Cloud
      color: orange
      percentage: 90
      description: Deploying to someone else's computer is my favorite

    - name: Writing code
      color: green
      percentage: 80
      description: C#, Node, Python,

    - name: Shell Scripting
      color: blue
      percentage: 90
      description: |
        I truly love PowerShell but Bash is close to my heart

    - name: Containerization
      color: white
      percentage: 85
      description: Write once, run anywhere. k8s and docker are my friends

    - name: Infrastructure as Code (IaC)
      color: pink
      percentage: 95
      description: Azure Bicep or Hashicorp Terraform are my go to for source controlled infrastructure.  We keep ARM in the wings for emergencies

    - name: YAML Pipelines
      color: gold
      percentage: 100
      description: GitHub Actions and Azure Pipelines are my jam

  softskills:
    - name: Mentoring
      color: red
      percentage: 100
      description: I love to teach and learn from others

    - name: Leadership
      color: orange
      percentage: 90
      description: Working with others to achieve a common goal is top on my list

  languages:
    - name: English
      color: gold
      percentage: 100

    - name: Latin
      percentage: 10
      description: Semper ubi sub ubi

  projects:
    - title: AWS to Azure Migration
      color: red
      description: Lift 'n Shift of entire AWS prod environment to Azure

    - title: Common IoT Ingress Platform
      color: gold
      description: Architected and implemented a common and extendable IoT ingress platform solution for kickstarting customer projects

    - title: IaC Module Library
      color: blue
      description: Created a library of reusable IaC modules for use across projects

  certifications:
    - certName: "Microsoft Certified: Azure Fundamentals, AZ-900"
      company: Microsoft
      date: 2021
      description: https://www.credly.com/badges/d934738b-bfc7-4cc8-8834-31dd6a3584b4
    - certName: "Microsoft Certified: Azure Developer Associate, AZ-204"
      company: Example Certifying Company
      date: 2022
      description: https://www.credly.com/badges/2837c812-6e62-4d13-86f4-9bcb392bf2f2
    - certName: "Microsoft Certified: DevOps Engineer Expert, AZ-400"
      company: Microsoft
      date: 2023
      description: https://learn.microsoft.com/en-us/users/austindelarosa-9331/credentials/ebefd65252f4d078

  # misc:
  #   #commandName: newcommand
  #   title: "This Section can have a different command name"
  #   titleColor: teal
  #   content: |
  #     Here the title and the content can have different colors
  #     The content can be multi

  #     line

  #     And spaces       will be respected as well
  #     This section will have the default command: misc
  #     but you can name it something else with the property
  #     commandName: <String>
  #     Give it a shot and try and uncomment the line
  #     commandName: newcommand
  #     now instead of misc you can execute the newcommand for this section
  #     Auto completion will know it too! :D

  #   contentColor: orange
