## Example Config file
BaseURL: "https://austindelarosa.com/"
theme: "terminalcv"
title: "atdlr"

params:
  description: "Austin DeLaRosa - Lead DevOps Engineer"
  prompt: "root@atdlr"
  promptColor: lightblue
  promptSimbols: ":~$"
  # promptSimbolsColor: grey
  startxLocation: https://twitter.com/lucashennessey
  # hideSocialName: true
  exitLocation: "about:blank"
  # hidesource: true
  greeting: |
    Welcome to my terminal cirriculum vitae

    Type 'help' for a list of available commands

  whois:
    name: "Austin DeLaRosa"
    profession: "Lead DevOps Engineer"
    location: "Cincinnati, Ohio"
    email: "austin.delarosa@gmail.com"
    homelink: "https://www.austindelarosa.com"
    description: |
      This site is under construction

  social:
    ## IF you want to keep them aligned just add spaces
    - name: "github"
      url: "          https://github.com/delarooster"
    - name: "linkedin"
      url: "        https://www.linkedin.com/in/austindelarosa"

  work:
    - jobTitle: Lead DevOps Engineer
      color: gold
      company: Mesh Systems
      location: remote
      date: August 2022 - Present
      #description: |

    - jobTitle: DevOps Engineer
      color: lightblue
      company: Mesh Systems
      location: remote
      date: August 2021 - August 2022
      #description: |

    - jobTitle: Software Engineer
      color: lightblue
      company: The David J. Joseph Company (DJJ)
      location: Cincinnati, Ohio
      date: January 2020 - August 2021
      #description: |

    - jobTitle: Software Engineer
      color: lightblue
      company: Organized Living
      location: Sharonville, Ohio
      date: 2019
      #description: |

    - jobTitle: Software Engineer
      color: lightblue
      company: Atricure
      location: Mason, Ohio
      date: 2018 - 2019
      #description: |

  education:
    - courseName: Tech Elevator
      color: blue
      description: |
        Computer Science

    - courseName: Butler University
      color: white
      description: |
        Master of Music

    - courseName: DePauw University
      color: gold
      description: |
        Bachelor of Music
        ITAP

  skills:
    - name: Skill 1
      percentage: 90
      Description: you can add a description

    - name: Skill 2
      percentage: 30
      #description: or you can leave it comented

    - name: Skill 3
      color: blue
      percentage: 50
      description: Skill names can have colors too

  softskills:
    - name: SoftSkill 1
      color: red
      percentage: 80
      #description:

    - name: SoftSkill 2
      #color:
      percentage: 90
      description: Description

  languages:
    - name: English
      color: gold
      percentage: 100

    - name: Latin
      percentage: 10
      description: Semper ubi sub ubi

  projects:
    - title: Project Red
      color: red
      date: since 2019
      link: https://example.com
      description: Describing red stuff

    - title: Project Blue
      color: blue
      date: since 2016
      link: https://example.com/blue
      #description: nothing to describe

    - title: Project Default
      date: Since 2017
      link: https://example.com/default
      #description: not there either

  certifications:
    - certName: "Microsoft Certified: DevOps Engineer Expert, AZ-400"
      company: Microsoft
      date: 2021
      description: https://learn.microsoft.com/en-us/credentials/certifications/devops-engineer/
    - certName: "Microsoft Certified: Azure Developer Associate, AZ-204"
      company: Example Certifying Company
      date: 2022
      description: https://learn.microsoft.com/en-us/credentials/certifications/azure-developer/
    - certName: "Microsoft Certified: Azure Fundamentals, AZ-900"
      company: Microsoft
      date: 2023
      description: https://learn.microsoft.com/en-us/credentials/certifications/exams/az-900/

  # misc:
  #   #commandName: newcommand
  #   title: "This Section can have a different command name"
  #   titleColor: teal
  #   content: |
  #     Here the title and the content can have different colors
  #     The content can be multi

  #     line

  #     And spaces       will be respected as well
  #     This section will have the default command: misc
  #     but you can name it something else with the property
  #     commandName: <String>
  #     Give it a shot and try and uncomment the line
  #     commandName: newcommand
  #     now instead of misc you can execute the newcommand for this section
  #     Auto completion will know it too! :D

  #   contentColor: orange
